/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppReposRouteImport } from './routes/_app/repos'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiGithubActionRouteImport } from './routes/api/github/action'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'
import { Route as AppPrOwnerRepoNumberRouteImport } from './routes/_app/pr.$owner.$repo.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppReposRoute = AppReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubActionRoute = ApiGithubActionRouteImport.update({
  id: '/api/github/action',
  path: '/api/github/action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPrOwnerRepoNumberRoute = AppPrOwnerRepoNumberRouteImport.update({
  id: '/pr/$owner/$repo/$number',
  path: '/pr/$owner/$repo/$number',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/inbox': typeof AppInboxRoute
  '/repos': typeof AppReposRoute
  '/settings': typeof AppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/action': typeof ApiGithubActionRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/pr/$owner/$repo/$number': typeof AppPrOwnerRepoNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/inbox': typeof AppInboxRoute
  '/repos': typeof AppReposRoute
  '/settings': typeof AppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/action': typeof ApiGithubActionRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/pr/$owner/$repo/$number': typeof AppPrOwnerRepoNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/repos': typeof AppReposRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/action': typeof ApiGithubActionRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/_app/pr/$owner/$repo/$number': typeof AppPrOwnerRepoNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/inbox'
    | '/repos'
    | '/settings'
    | '/api/auth/$'
    | '/api/github/action'
    | '/api/github/webhook'
    | '/pr/$owner/$repo/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/inbox'
    | '/repos'
    | '/settings'
    | '/api/auth/$'
    | '/api/github/action'
    | '/api/github/webhook'
    | '/pr/$owner/$repo/$number'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/demo'
    | '/login'
    | '/_app/inbox'
    | '/_app/repos'
    | '/_app/settings'
    | '/api/auth/$'
    | '/api/github/action'
    | '/api/github/webhook'
    | '/_app/pr/$owner/$repo/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGithubActionRoute: typeof ApiGithubActionRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repos': {
      id: '/_app/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof AppReposRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/action': {
      id: '/api/github/action'
      path: '/api/github/action'
      fullPath: '/api/github/action'
      preLoaderRoute: typeof ApiGithubActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pr/$owner/$repo/$number': {
      id: '/_app/pr/$owner/$repo/$number'
      path: '/pr/$owner/$repo/$number'
      fullPath: '/pr/$owner/$repo/$number'
      preLoaderRoute: typeof AppPrOwnerRepoNumberRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInboxRoute: typeof AppInboxRoute
  AppReposRoute: typeof AppReposRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppPrOwnerRepoNumberRoute: typeof AppPrOwnerRepoNumberRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInboxRoute: AppInboxRoute,
  AppReposRoute: AppReposRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppPrOwnerRepoNumberRoute: AppPrOwnerRepoNumberRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGithubActionRoute: ApiGithubActionRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
